#!/usr/bin/env python3
"""
Generate larger GPU Group table for GRP_SIZE=2048

This computes G, 2G, 3G, ... 1024G using secp256k1 curve arithmetic
"""

import json
import ssl
import uuid
import websocket
import time

JUPYTER_URL = "74.48.140.178:25349"
TOKEN = "afebbf7c1170dd3aeecb6dd1e1bf3930efa6420680734908e23cc38dc3ef63f7"
KERNEL_ID = "572a883c-5fbf-429a-b569-e3073acde909"

GENERATE_CODE = '''
import os
import time

os.chdir("/workspace/Bot/vanitysearch_analysis")

print("=" * 70)
print("GENERATING LARGER GENERATOR TABLE FOR GRP_SIZE=2048")
print("=" * 70)

# secp256k1 parameters
p = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
# Generator point G
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8

def modinv(a, m=p):
    """Modular inverse using extended Euclidean algorithm"""
    if a < 0:
        a = a % m
    g, x, _ = extended_gcd(a, m)
    if g != 1:
        raise Exception('Modular inverse does not exist')
    return x % m

def extended_gcd(a, b):
    if a == 0:
        return b, 0, 1
    gcd, x1, y1 = extended_gcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return gcd, x, y

def point_add(x1, y1, x2, y2):
    """Add two points on secp256k1"""
    if x1 == x2 and y1 == y2:
        # Point doubling
        s = (3 * x1 * x1 * modinv(2 * y1)) % p
    else:
        # Point addition
        s = ((y2 - y1) * modinv(x2 - x1)) % p

    x3 = (s * s - x1 - x2) % p
    y3 = (s * (x1 - x3) - y1) % p
    return x3, y3

def to_c64_str(val):
    """Convert 256-bit integer to C uint64_t array string"""
    words = []
    for i in range(4):
        word = (val >> (64 * i)) & 0xFFFFFFFFFFFFFFFF
        words.append(f"0x{word:016X}ULL")
    return "{" + ",".join(words) + "}"

print("Computing generator multiples (this takes a minute)...")
start = time.time()

# Compute nG for n = 1 to 1024 (for GRP_SIZE=2048, we need GRP_SIZE/2 points)
points = []
x, y = Gx, Gy
points.append((x, y))

for i in range(1, 1024):
    x, y = point_add(x, y, Gx, Gy)
    points.append((x, y))
    if (i + 1) % 100 == 0:
        print(f"  Computed {i + 1}/1024 points...")

print(f"Computation took {time.time() - start:.1f} seconds")

# Compute 2048*G for _2Gnx, _2Gny
x, y = Gx, Gy
for i in range(2047):
    x, y = point_add(x, y, Gx, Gy)
_2048Gx = x
_2048Gy = y

print(f"Computed 2048*G")

# Generate GPUGroup.h
print("\\nGenerating GPU/GPUGroup.h...")

header = '// GPUGroup.h - Generated for GRP_SIZE=2048\\n'
header += '// Generator table contains G, 2G, 3G, ..., 1024G\\n'
header += '// Auto-generated by Terragon Labs optimization script\\n\\n'
header += '#define GRP_SIZE 2048\\n\\n'
header += '// _2Gn = GRP_SIZE*G (2048*G)\\n'
header += '__device__ __constant__ uint64_t _2Gnx[4] = ' + to_c64_str(_2048Gx) + ';\\n'
header += '__device__ __constant__ uint64_t _2Gny[4] = ' + to_c64_str(_2048Gy) + ';\\n\\n'
header += '// SecpK1 Generator table (Contains G,2G,3G,...,(GRP_SIZE/2)G = 1024G)\\n'
header += '__device__ __constant__ uint64_t Gx[][4] = {\\n'

for i, (px, py) in enumerate(points):
    header += f"  {to_c64_str(px)},\\n"

header += '};\\n'
header += '__device__ __constant__ uint64_t Gy[][4] = {\\n'

for i, (px, py) in enumerate(points):
    header += f"  {to_c64_str(py)},\\n"

header += '};\\n\\n'

# Backup and write
import shutil
if os.path.exists("GPU/GPUGroup.h"):
    shutil.copy("GPU/GPUGroup.h", "GPU/GPUGroup.h.1024")

with open("GPU/GPUGroup.h", "w") as f:
    f.write(header)

print("Written GPU/GPUGroup.h with 1024 generator points")

# Verify file size
stat = os.stat("GPU/GPUGroup.h")
print(f"File size: {stat.st_size} bytes")

# Now we need to clean and rebuild
print("\\nCleaning build...")
import subprocess
subprocess.run(["make", "clean"], capture_output=True)
subprocess.run(["rm", "-rf", "obj"], capture_output=True)
subprocess.run(["mkdir", "-p", "obj/GPU", "obj/hash"], capture_output=True)

print("\\nRebuilding VanitySearch with GRP_SIZE=2048...")
result = subprocess.run(
    ["make", "gpu=1", "CCAP=89", "-j4"],
    capture_output=True, text=True
)

if result.returncode == 0:
    print("BUILD SUCCESSFUL!")
    stat = os.stat("VanitySearch")
    print(f"Binary size: {stat.st_size} bytes")
else:
    print("BUILD FAILED!")
    print(result.stderr[-2000:])
    # Restore backup
    shutil.copy("GPU/GPUGroup.h.1024", "GPU/GPUGroup.h")
    print("Restored original GPUGroup.h")
'''

def execute():
    ws_url = f"wss://{JUPYTER_URL}/api/kernels/{KERNEL_ID}/channels?token={TOKEN}"
    ws = websocket.create_connection(ws_url, sslopt={"cert_reqs": ssl.CERT_NONE})

    msg_id = str(uuid.uuid4())
    req = {
        "header": {"msg_id": msg_id, "username": "user", "session": str(uuid.uuid4()),
                   "msg_type": "execute_request", "version": "5.3"},
        "parent_header": {}, "metadata": {},
        "content": {"code": GENERATE_CODE, "silent": False, "store_history": True,
                   "user_expressions": {}, "allow_stdin": False, "stop_on_error": True},
        "buffers": [], "channel": "shell"
    }

    ws.send(json.dumps(req))
    print("Generating larger generator table...\n")

    start = time.time()
    while time.time() - start < 300:
        try:
            msg = ws.recv()
            r = json.loads(msg)
            if r.get("msg_type") == "stream":
                print(r["content"]["text"], end="")
            elif r.get("msg_type") == "error":
                print(f"ERROR: {r['content']['ename']}: {r['content']['evalue']}")
                break
            elif r.get("msg_type") == "execute_reply":
                break
        except Exception as e:
            print(f"Error: {e}")
            break

    ws.close()

if __name__ == "__main__":
    execute()
